root: true
env: { node: true, es2021: true }
extends:
  - 'eslint:recommended'
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:vue-pug/vue3-recommended'
  - 'prettier'
  - '@vue/prettier'
parserOptions: { ecmaVersion: 'latest', sourceType: 'module' }
plugins: ['vue', '@typescript-eslint']
rules: {
    # コンソールログの出力に関して
    no-console: off,
    # 複合語のみコンポーネント名とするか
    vue/multi-word-component-names: off,
  }
